#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

python md2pdf.py
RST=$?
if [ $RST -ne 0 ]; then
		echo "md2pdf.py failed with exit code $RST"
		echo "Please fix the errors and try committing again."
		exit $RST
fi
